pipeline {
    agent any
          stage('Git-Checkout') {
           steps {
                // Git checkout step
                git credentialsId: 'tomcatcred', url: 'https://github.com/dkadmin/tomcat-project.git'
                echo "Checkout successful"
            }
        }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
